
title: Happiness Report
email: nigu8394@colorado.edu
description: >-
Sudoku solvers using deep learning models. 
baseurl: "/sudoku-CNN" # the subpath of your site, e.g. /blog
url: "https://sammy22.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
theme: minima
plugins:
  - jekyll-feed